// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: pkg/rpc/proto/rpc_server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EndNodeAccess_GetUsers_FullMethodName             = "/proto.EndNodeAccess/GetUsers"
	EndNodeAccess_GetProfile_FullMethodName           = "/proto.EndNodeAccess/GetProfile"
	EndNodeAccess_AddUsers_FullMethodName             = "/proto.EndNodeAccess/AddUsers"
	EndNodeAccess_DeleteUsers_FullMethodName          = "/proto.EndNodeAccess/DeleteUsers"
	EndNodeAccess_UpdateUsers_FullMethodName          = "/proto.EndNodeAccess/UpdateUsers"
	EndNodeAccess_ResetUser_FullMethodName            = "/proto.EndNodeAccess/ResetUser"
	EndNodeAccess_GetSub_FullMethodName               = "/proto.EndNodeAccess/GetSub"
	EndNodeAccess_GetBandWidthStats_FullMethodName    = "/proto.EndNodeAccess/GetBandWidthStats"
	EndNodeAccess_HeartBeat_FullMethodName            = "/proto.EndNodeAccess/HeartBeat"
	EndNodeAccess_RegisterNode_FullMethodName         = "/proto.EndNodeAccess/RegisterNode"
	EndNodeAccess_SetGatewayModel_FullMethodName      = "/proto.EndNodeAccess/SetGatewayModel"
	EndNodeAccess_SetPingCheck_FullMethodName         = "/proto.EndNodeAccess/SetPingCheck"
	EndNodeAccess_AddInbound_FullMethodName           = "/proto.EndNodeAccess/AddInbound"
	EndNodeAccess_DeleteInbound_FullMethodName        = "/proto.EndNodeAccess/DeleteInbound"
	EndNodeAccess_TransferInbound_FullMethodName      = "/proto.EndNodeAccess/TransferInbound"
	EndNodeAccess_CopyInbound_FullMethodName          = "/proto.EndNodeAccess/CopyInbound"
	EndNodeAccess_CopyUser_FullMethodName             = "/proto.EndNodeAccess/CopyUser"
	EndNodeAccess_GetInbound_FullMethodName           = "/proto.EndNodeAccess/GetInbound"
	EndNodeAccess_ListInbound_FullMethodName          = "/proto.EndNodeAccess/ListInbound"
	EndNodeAccess_DeleteInboundByName_FullMethodName  = "/proto.EndNodeAccess/DeleteInboundByName"
	EndNodeAccess_UpdateProxy_FullMethodName          = "/proto.EndNodeAccess/UpdateProxy"
	EndNodeAccess_AddAdaptiveConfig_FullMethodName    = "/proto.EndNodeAccess/AddAdaptiveConfig"
	EndNodeAccess_DeleteAdaptiveConfig_FullMethodName = "/proto.EndNodeAccess/DeleteAdaptiveConfig"
	EndNodeAccess_Adaptive_FullMethodName             = "/proto.EndNodeAccess/Adaptive"
	EndNodeAccess_FastAddInbound_FullMethodName       = "/proto.EndNodeAccess/FastAddInbound"
	EndNodeAccess_ObtainNewCert_FullMethodName        = "/proto.EndNodeAccess/ObtainNewCert"
	EndNodeAccess_TransferCert_FullMethodName         = "/proto.EndNodeAccess/TransferCert"
	EndNodeAccess_GetCerts_FullMethodName             = "/proto.EndNodeAccess/GetCerts"
	EndNodeAccess_DeleteCert_FullMethodName           = "/proto.EndNodeAccess/DeleteCert"
	EndNodeAccess_GetPingMetric_FullMethodName        = "/proto.EndNodeAccess/GetPingMetric"
	EndNodeAccess_GetNodeMetric_FullMethodName        = "/proto.EndNodeAccess/GetNodeMetric"
	EndNodeAccess_GetNodeGroups_FullMethodName        = "/proto.EndNodeAccess/GetNodeGroups"
	EndNodeAccess_SetNodeGroups_FullMethodName        = "/proto.EndNodeAccess/SetNodeGroups"
	EndNodeAccess_UpsertClusterUsers_FullMethodName   = "/proto.EndNodeAccess/UpsertClusterUsers"
	EndNodeAccess_GetStatus_FullMethodName            = "/proto.EndNodeAccess/GetStatus"
)

// EndNodeAccessClient is the client API for EndNodeAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndNodeAccessClient interface {
	// user
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersRsp, error)
	GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileRsp, error)
	AddUsers(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error)
	DeleteUsers(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error)
	UpdateUsers(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error)
	ResetUser(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error)
	GetSub(ctx context.Context, in *GetSubReq, opts ...grpc.CallOption) (*GetSubRsp, error)
	GetBandWidthStats(ctx context.Context, in *GetBandwidthStatsReq, opts ...grpc.CallOption) (*GetBandwidthStatsRsp, error)
	// system
	HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatRsp, error)
	RegisterNode(ctx context.Context, in *RegisterNodeReq, opts ...grpc.CallOption) (*RegisterNodeRsp, error)
	SetGatewayModel(ctx context.Context, in *SetGatewayModelReq, opts ...grpc.CallOption) (*SetGatewayModelRsp, error)
	SetPingCheck(ctx context.Context, in *SetPingCheckReq, opts ...grpc.CallOption) (*SetPingCheckRsp, error)
	// inbound
	AddInbound(ctx context.Context, in *InboundOpReq, opts ...grpc.CallOption) (*InboundOpRsp, error)
	DeleteInbound(ctx context.Context, in *InboundOpReq, opts ...grpc.CallOption) (*InboundOpRsp, error)
	TransferInbound(ctx context.Context, in *TransferInboundReq, opts ...grpc.CallOption) (*InboundOpRsp, error)
	CopyInbound(ctx context.Context, in *CopyInboundReq, opts ...grpc.CallOption) (*InboundOpRsp, error)
	CopyUser(ctx context.Context, in *CopyUserReq, opts ...grpc.CallOption) (*InboundOpRsp, error)
	GetInbound(ctx context.Context, in *GetInboundReq, opts ...grpc.CallOption) (*GetInboundRsp, error)
	ListInbound(ctx context.Context, in *ListInboundReq, opts ...grpc.CallOption) (*ListInboundRsp, error)
	DeleteInboundByName(ctx context.Context, in *DeleteInboundByNameReq, opts ...grpc.CallOption) (*InboundOpRsp, error)
	// proxy
	UpdateProxy(ctx context.Context, in *UpdateProxyReq, opts ...grpc.CallOption) (*UpdateProxyRsp, error)
	AddAdaptiveConfig(ctx context.Context, in *AdaptiveOpReq, opts ...grpc.CallOption) (*AdaptiveRsp, error)
	DeleteAdaptiveConfig(ctx context.Context, in *AdaptiveOpReq, opts ...grpc.CallOption) (*AdaptiveRsp, error)
	Adaptive(ctx context.Context, in *AdaptiveReq, opts ...grpc.CallOption) (*AdaptiveRsp, error)
	FastAddInbound(ctx context.Context, in *FastAddInboundReq, opts ...grpc.CallOption) (*FastAddInboundRsp, error)
	// cert
	ObtainNewCert(ctx context.Context, in *ObtainNewCertReq, opts ...grpc.CallOption) (*ObtainNewCertRsp, error)
	TransferCert(ctx context.Context, in *TransferCertReq, opts ...grpc.CallOption) (*TransferCertRsp, error)
	GetCerts(ctx context.Context, in *GetCertsReq, opts ...grpc.CallOption) (*GetCertsRsp, error)
	DeleteCert(ctx context.Context, in *DeleteCertReq, opts ...grpc.CallOption) (*DeleteCertRsp, error)
	// / metric
	GetPingMetric(ctx context.Context, in *GetPingMetricReq, opts ...grpc.CallOption) (*GetPingMetricRsp, error)
	GetNodeMetric(ctx context.Context, in *GetNodeMetricReq, opts ...grpc.CallOption) (*GetNodeMetricRsp, error)
	// cluster user
	GetNodeGroups(ctx context.Context, in *GetNodeGroupsReq, opts ...grpc.CallOption) (*GetNodeGroupsRsp, error)
	SetNodeGroups(ctx context.Context, in *SetNodeGroupsReq, opts ...grpc.CallOption) (*SetNodeGroupsRsp, error)
	UpsertClusterUsers(ctx context.Context, in *UpsertClusterUsersReq, opts ...grpc.CallOption) (*UpsertClusterUsersRsp, error)
	// status
	GetStatus(ctx context.Context, in *GetStatusReq, opts ...grpc.CallOption) (*GetStatusRsp, error)
}

type endNodeAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewEndNodeAccessClient(cc grpc.ClientConnInterface) EndNodeAccessClient {
	return &endNodeAccessClient{cc}
}

func (c *endNodeAccessClient) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) AddUsers(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_AddUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) DeleteUsers(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_DeleteUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) UpdateUsers(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_UpdateUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) ResetUser(ctx context.Context, in *UserOpReq, opts ...grpc.CallOption) (*UserOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_ResetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetSub(ctx context.Context, in *GetSubReq, opts ...grpc.CallOption) (*GetSubRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetSub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetBandWidthStats(ctx context.Context, in *GetBandwidthStatsReq, opts ...grpc.CallOption) (*GetBandwidthStatsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBandwidthStatsRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetBandWidthStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartBeatRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_HeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) RegisterNode(ctx context.Context, in *RegisterNodeReq, opts ...grpc.CallOption) (*RegisterNodeRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) SetGatewayModel(ctx context.Context, in *SetGatewayModelReq, opts ...grpc.CallOption) (*SetGatewayModelRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGatewayModelRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_SetGatewayModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) SetPingCheck(ctx context.Context, in *SetPingCheckReq, opts ...grpc.CallOption) (*SetPingCheckRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPingCheckRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_SetPingCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) AddInbound(ctx context.Context, in *InboundOpReq, opts ...grpc.CallOption) (*InboundOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_AddInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) DeleteInbound(ctx context.Context, in *InboundOpReq, opts ...grpc.CallOption) (*InboundOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_DeleteInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) TransferInbound(ctx context.Context, in *TransferInboundReq, opts ...grpc.CallOption) (*InboundOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_TransferInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) CopyInbound(ctx context.Context, in *CopyInboundReq, opts ...grpc.CallOption) (*InboundOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_CopyInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) CopyUser(ctx context.Context, in *CopyUserReq, opts ...grpc.CallOption) (*InboundOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_CopyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetInbound(ctx context.Context, in *GetInboundReq, opts ...grpc.CallOption) (*GetInboundRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInboundRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) ListInbound(ctx context.Context, in *ListInboundReq, opts ...grpc.CallOption) (*ListInboundRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInboundRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_ListInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) DeleteInboundByName(ctx context.Context, in *DeleteInboundByNameReq, opts ...grpc.CallOption) (*InboundOpRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboundOpRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_DeleteInboundByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) UpdateProxy(ctx context.Context, in *UpdateProxyReq, opts ...grpc.CallOption) (*UpdateProxyRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProxyRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_UpdateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) AddAdaptiveConfig(ctx context.Context, in *AdaptiveOpReq, opts ...grpc.CallOption) (*AdaptiveRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdaptiveRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_AddAdaptiveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) DeleteAdaptiveConfig(ctx context.Context, in *AdaptiveOpReq, opts ...grpc.CallOption) (*AdaptiveRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdaptiveRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_DeleteAdaptiveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) Adaptive(ctx context.Context, in *AdaptiveReq, opts ...grpc.CallOption) (*AdaptiveRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdaptiveRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_Adaptive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) FastAddInbound(ctx context.Context, in *FastAddInboundReq, opts ...grpc.CallOption) (*FastAddInboundRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FastAddInboundRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_FastAddInbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) ObtainNewCert(ctx context.Context, in *ObtainNewCertReq, opts ...grpc.CallOption) (*ObtainNewCertRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtainNewCertRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_ObtainNewCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) TransferCert(ctx context.Context, in *TransferCertReq, opts ...grpc.CallOption) (*TransferCertRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferCertRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_TransferCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetCerts(ctx context.Context, in *GetCertsReq, opts ...grpc.CallOption) (*GetCertsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertsRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetCerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) DeleteCert(ctx context.Context, in *DeleteCertReq, opts ...grpc.CallOption) (*DeleteCertRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCertRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_DeleteCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetPingMetric(ctx context.Context, in *GetPingMetricReq, opts ...grpc.CallOption) (*GetPingMetricRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPingMetricRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetPingMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetNodeMetric(ctx context.Context, in *GetNodeMetricReq, opts ...grpc.CallOption) (*GetNodeMetricRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeMetricRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetNodeMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetNodeGroups(ctx context.Context, in *GetNodeGroupsReq, opts ...grpc.CallOption) (*GetNodeGroupsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeGroupsRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetNodeGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) SetNodeGroups(ctx context.Context, in *SetNodeGroupsReq, opts ...grpc.CallOption) (*SetNodeGroupsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNodeGroupsRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_SetNodeGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) UpsertClusterUsers(ctx context.Context, in *UpsertClusterUsersReq, opts ...grpc.CallOption) (*UpsertClusterUsersRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertClusterUsersRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_UpsertClusterUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endNodeAccessClient) GetStatus(ctx context.Context, in *GetStatusReq, opts ...grpc.CallOption) (*GetStatusRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusRsp)
	err := c.cc.Invoke(ctx, EndNodeAccess_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndNodeAccessServer is the server API for EndNodeAccess service.
// All implementations must embed UnimplementedEndNodeAccessServer
// for forward compatibility.
type EndNodeAccessServer interface {
	// user
	GetUsers(context.Context, *GetUsersReq) (*GetUsersRsp, error)
	GetProfile(context.Context, *GetProfileReq) (*GetProfileRsp, error)
	AddUsers(context.Context, *UserOpReq) (*UserOpRsp, error)
	DeleteUsers(context.Context, *UserOpReq) (*UserOpRsp, error)
	UpdateUsers(context.Context, *UserOpReq) (*UserOpRsp, error)
	ResetUser(context.Context, *UserOpReq) (*UserOpRsp, error)
	GetSub(context.Context, *GetSubReq) (*GetSubRsp, error)
	GetBandWidthStats(context.Context, *GetBandwidthStatsReq) (*GetBandwidthStatsRsp, error)
	// system
	HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatRsp, error)
	RegisterNode(context.Context, *RegisterNodeReq) (*RegisterNodeRsp, error)
	SetGatewayModel(context.Context, *SetGatewayModelReq) (*SetGatewayModelRsp, error)
	SetPingCheck(context.Context, *SetPingCheckReq) (*SetPingCheckRsp, error)
	// inbound
	AddInbound(context.Context, *InboundOpReq) (*InboundOpRsp, error)
	DeleteInbound(context.Context, *InboundOpReq) (*InboundOpRsp, error)
	TransferInbound(context.Context, *TransferInboundReq) (*InboundOpRsp, error)
	CopyInbound(context.Context, *CopyInboundReq) (*InboundOpRsp, error)
	CopyUser(context.Context, *CopyUserReq) (*InboundOpRsp, error)
	GetInbound(context.Context, *GetInboundReq) (*GetInboundRsp, error)
	ListInbound(context.Context, *ListInboundReq) (*ListInboundRsp, error)
	DeleteInboundByName(context.Context, *DeleteInboundByNameReq) (*InboundOpRsp, error)
	// proxy
	UpdateProxy(context.Context, *UpdateProxyReq) (*UpdateProxyRsp, error)
	AddAdaptiveConfig(context.Context, *AdaptiveOpReq) (*AdaptiveRsp, error)
	DeleteAdaptiveConfig(context.Context, *AdaptiveOpReq) (*AdaptiveRsp, error)
	Adaptive(context.Context, *AdaptiveReq) (*AdaptiveRsp, error)
	FastAddInbound(context.Context, *FastAddInboundReq) (*FastAddInboundRsp, error)
	// cert
	ObtainNewCert(context.Context, *ObtainNewCertReq) (*ObtainNewCertRsp, error)
	TransferCert(context.Context, *TransferCertReq) (*TransferCertRsp, error)
	GetCerts(context.Context, *GetCertsReq) (*GetCertsRsp, error)
	DeleteCert(context.Context, *DeleteCertReq) (*DeleteCertRsp, error)
	// / metric
	GetPingMetric(context.Context, *GetPingMetricReq) (*GetPingMetricRsp, error)
	GetNodeMetric(context.Context, *GetNodeMetricReq) (*GetNodeMetricRsp, error)
	// cluster user
	GetNodeGroups(context.Context, *GetNodeGroupsReq) (*GetNodeGroupsRsp, error)
	SetNodeGroups(context.Context, *SetNodeGroupsReq) (*SetNodeGroupsRsp, error)
	UpsertClusterUsers(context.Context, *UpsertClusterUsersReq) (*UpsertClusterUsersRsp, error)
	// status
	GetStatus(context.Context, *GetStatusReq) (*GetStatusRsp, error)
	mustEmbedUnimplementedEndNodeAccessServer()
}

// UnimplementedEndNodeAccessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndNodeAccessServer struct{}

func (UnimplementedEndNodeAccessServer) GetUsers(context.Context, *GetUsersReq) (*GetUsersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedEndNodeAccessServer) GetProfile(context.Context, *GetProfileReq) (*GetProfileRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedEndNodeAccessServer) AddUsers(context.Context, *UserOpReq) (*UserOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUsers not implemented")
}
func (UnimplementedEndNodeAccessServer) DeleteUsers(context.Context, *UserOpReq) (*UserOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUsers not implemented")
}
func (UnimplementedEndNodeAccessServer) UpdateUsers(context.Context, *UserOpReq) (*UserOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUsers not implemented")
}
func (UnimplementedEndNodeAccessServer) ResetUser(context.Context, *UserOpReq) (*UserOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetUser not implemented")
}
func (UnimplementedEndNodeAccessServer) GetSub(context.Context, *GetSubReq) (*GetSubRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSub not implemented")
}
func (UnimplementedEndNodeAccessServer) GetBandWidthStats(context.Context, *GetBandwidthStatsReq) (*GetBandwidthStatsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBandWidthStats not implemented")
}
func (UnimplementedEndNodeAccessServer) HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedEndNodeAccessServer) RegisterNode(context.Context, *RegisterNodeReq) (*RegisterNodeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedEndNodeAccessServer) SetGatewayModel(context.Context, *SetGatewayModelReq) (*SetGatewayModelRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGatewayModel not implemented")
}
func (UnimplementedEndNodeAccessServer) SetPingCheck(context.Context, *SetPingCheckReq) (*SetPingCheckRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPingCheck not implemented")
}
func (UnimplementedEndNodeAccessServer) AddInbound(context.Context, *InboundOpReq) (*InboundOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) DeleteInbound(context.Context, *InboundOpReq) (*InboundOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) TransferInbound(context.Context, *TransferInboundReq) (*InboundOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) CopyInbound(context.Context, *CopyInboundReq) (*InboundOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) CopyUser(context.Context, *CopyUserReq) (*InboundOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyUser not implemented")
}
func (UnimplementedEndNodeAccessServer) GetInbound(context.Context, *GetInboundReq) (*GetInboundRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) ListInbound(context.Context, *ListInboundReq) (*ListInboundRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) DeleteInboundByName(context.Context, *DeleteInboundByNameReq) (*InboundOpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInboundByName not implemented")
}
func (UnimplementedEndNodeAccessServer) UpdateProxy(context.Context, *UpdateProxyReq) (*UpdateProxyRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProxy not implemented")
}
func (UnimplementedEndNodeAccessServer) AddAdaptiveConfig(context.Context, *AdaptiveOpReq) (*AdaptiveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAdaptiveConfig not implemented")
}
func (UnimplementedEndNodeAccessServer) DeleteAdaptiveConfig(context.Context, *AdaptiveOpReq) (*AdaptiveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdaptiveConfig not implemented")
}
func (UnimplementedEndNodeAccessServer) Adaptive(context.Context, *AdaptiveReq) (*AdaptiveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Adaptive not implemented")
}
func (UnimplementedEndNodeAccessServer) FastAddInbound(context.Context, *FastAddInboundReq) (*FastAddInboundRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FastAddInbound not implemented")
}
func (UnimplementedEndNodeAccessServer) ObtainNewCert(context.Context, *ObtainNewCertReq) (*ObtainNewCertRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtainNewCert not implemented")
}
func (UnimplementedEndNodeAccessServer) TransferCert(context.Context, *TransferCertReq) (*TransferCertRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferCert not implemented")
}
func (UnimplementedEndNodeAccessServer) GetCerts(context.Context, *GetCertsReq) (*GetCertsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCerts not implemented")
}
func (UnimplementedEndNodeAccessServer) DeleteCert(context.Context, *DeleteCertReq) (*DeleteCertRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCert not implemented")
}
func (UnimplementedEndNodeAccessServer) GetPingMetric(context.Context, *GetPingMetricReq) (*GetPingMetricRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPingMetric not implemented")
}
func (UnimplementedEndNodeAccessServer) GetNodeMetric(context.Context, *GetNodeMetricReq) (*GetNodeMetricRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeMetric not implemented")
}
func (UnimplementedEndNodeAccessServer) GetNodeGroups(context.Context, *GetNodeGroupsReq) (*GetNodeGroupsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeGroups not implemented")
}
func (UnimplementedEndNodeAccessServer) SetNodeGroups(context.Context, *SetNodeGroupsReq) (*SetNodeGroupsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNodeGroups not implemented")
}
func (UnimplementedEndNodeAccessServer) UpsertClusterUsers(context.Context, *UpsertClusterUsersReq) (*UpsertClusterUsersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertClusterUsers not implemented")
}
func (UnimplementedEndNodeAccessServer) GetStatus(context.Context, *GetStatusReq) (*GetStatusRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEndNodeAccessServer) mustEmbedUnimplementedEndNodeAccessServer() {}
func (UnimplementedEndNodeAccessServer) testEmbeddedByValue()                       {}

// UnsafeEndNodeAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndNodeAccessServer will
// result in compilation errors.
type UnsafeEndNodeAccessServer interface {
	mustEmbedUnimplementedEndNodeAccessServer()
}

func RegisterEndNodeAccessServer(s grpc.ServiceRegistrar, srv EndNodeAccessServer) {
	// If the following call pancis, it indicates UnimplementedEndNodeAccessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EndNodeAccess_ServiceDesc, srv)
}

func _EndNodeAccess_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetUsers(ctx, req.(*GetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetProfile(ctx, req.(*GetProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_AddUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).AddUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_AddUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).AddUsers(ctx, req.(*UserOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_DeleteUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).DeleteUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_DeleteUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).DeleteUsers(ctx, req.(*UserOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_UpdateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).UpdateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_UpdateUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).UpdateUsers(ctx, req.(*UserOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_ResetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).ResetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_ResetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).ResetUser(ctx, req.(*UserOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetSub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetSub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetSub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetSub(ctx, req.(*GetSubReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetBandWidthStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBandwidthStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetBandWidthStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetBandWidthStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetBandWidthStats(ctx, req.(*GetBandwidthStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).HeartBeat(ctx, req.(*HeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).RegisterNode(ctx, req.(*RegisterNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_SetGatewayModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGatewayModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).SetGatewayModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_SetGatewayModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).SetGatewayModel(ctx, req.(*SetGatewayModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_SetPingCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPingCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).SetPingCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_SetPingCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).SetPingCheck(ctx, req.(*SetPingCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_AddInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).AddInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_AddInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).AddInbound(ctx, req.(*InboundOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_DeleteInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).DeleteInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_DeleteInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).DeleteInbound(ctx, req.(*InboundOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_TransferInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferInboundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).TransferInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_TransferInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).TransferInbound(ctx, req.(*TransferInboundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_CopyInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyInboundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).CopyInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_CopyInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).CopyInbound(ctx, req.(*CopyInboundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_CopyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).CopyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_CopyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).CopyUser(ctx, req.(*CopyUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInboundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetInbound(ctx, req.(*GetInboundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_ListInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInboundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).ListInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_ListInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).ListInbound(ctx, req.(*ListInboundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_DeleteInboundByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInboundByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).DeleteInboundByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_DeleteInboundByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).DeleteInboundByName(ctx, req.(*DeleteInboundByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_UpdateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProxyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).UpdateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_UpdateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).UpdateProxy(ctx, req.(*UpdateProxyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_AddAdaptiveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdaptiveOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).AddAdaptiveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_AddAdaptiveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).AddAdaptiveConfig(ctx, req.(*AdaptiveOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_DeleteAdaptiveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdaptiveOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).DeleteAdaptiveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_DeleteAdaptiveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).DeleteAdaptiveConfig(ctx, req.(*AdaptiveOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_Adaptive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdaptiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).Adaptive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_Adaptive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).Adaptive(ctx, req.(*AdaptiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_FastAddInbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FastAddInboundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).FastAddInbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_FastAddInbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).FastAddInbound(ctx, req.(*FastAddInboundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_ObtainNewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtainNewCertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).ObtainNewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_ObtainNewCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).ObtainNewCert(ctx, req.(*ObtainNewCertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_TransferCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferCertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).TransferCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_TransferCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).TransferCert(ctx, req.(*TransferCertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetCerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetCerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetCerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetCerts(ctx, req.(*GetCertsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_DeleteCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).DeleteCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_DeleteCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).DeleteCert(ctx, req.(*DeleteCertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetPingMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPingMetricReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetPingMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetPingMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetPingMetric(ctx, req.(*GetPingMetricReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetNodeMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeMetricReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetNodeMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetNodeMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetNodeMetric(ctx, req.(*GetNodeMetricReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetNodeGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetNodeGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetNodeGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetNodeGroups(ctx, req.(*GetNodeGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_SetNodeGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).SetNodeGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_SetNodeGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).SetNodeGroups(ctx, req.(*SetNodeGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_UpsertClusterUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertClusterUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).UpsertClusterUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_UpsertClusterUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).UpsertClusterUsers(ctx, req.(*UpsertClusterUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndNodeAccess_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndNodeAccessServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndNodeAccess_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndNodeAccessServer).GetStatus(ctx, req.(*GetStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EndNodeAccess_ServiceDesc is the grpc.ServiceDesc for EndNodeAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndNodeAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EndNodeAccess",
	HandlerType: (*EndNodeAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _EndNodeAccess_GetUsers_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _EndNodeAccess_GetProfile_Handler,
		},
		{
			MethodName: "AddUsers",
			Handler:    _EndNodeAccess_AddUsers_Handler,
		},
		{
			MethodName: "DeleteUsers",
			Handler:    _EndNodeAccess_DeleteUsers_Handler,
		},
		{
			MethodName: "UpdateUsers",
			Handler:    _EndNodeAccess_UpdateUsers_Handler,
		},
		{
			MethodName: "ResetUser",
			Handler:    _EndNodeAccess_ResetUser_Handler,
		},
		{
			MethodName: "GetSub",
			Handler:    _EndNodeAccess_GetSub_Handler,
		},
		{
			MethodName: "GetBandWidthStats",
			Handler:    _EndNodeAccess_GetBandWidthStats_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _EndNodeAccess_HeartBeat_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _EndNodeAccess_RegisterNode_Handler,
		},
		{
			MethodName: "SetGatewayModel",
			Handler:    _EndNodeAccess_SetGatewayModel_Handler,
		},
		{
			MethodName: "SetPingCheck",
			Handler:    _EndNodeAccess_SetPingCheck_Handler,
		},
		{
			MethodName: "AddInbound",
			Handler:    _EndNodeAccess_AddInbound_Handler,
		},
		{
			MethodName: "DeleteInbound",
			Handler:    _EndNodeAccess_DeleteInbound_Handler,
		},
		{
			MethodName: "TransferInbound",
			Handler:    _EndNodeAccess_TransferInbound_Handler,
		},
		{
			MethodName: "CopyInbound",
			Handler:    _EndNodeAccess_CopyInbound_Handler,
		},
		{
			MethodName: "CopyUser",
			Handler:    _EndNodeAccess_CopyUser_Handler,
		},
		{
			MethodName: "GetInbound",
			Handler:    _EndNodeAccess_GetInbound_Handler,
		},
		{
			MethodName: "ListInbound",
			Handler:    _EndNodeAccess_ListInbound_Handler,
		},
		{
			MethodName: "DeleteInboundByName",
			Handler:    _EndNodeAccess_DeleteInboundByName_Handler,
		},
		{
			MethodName: "UpdateProxy",
			Handler:    _EndNodeAccess_UpdateProxy_Handler,
		},
		{
			MethodName: "AddAdaptiveConfig",
			Handler:    _EndNodeAccess_AddAdaptiveConfig_Handler,
		},
		{
			MethodName: "DeleteAdaptiveConfig",
			Handler:    _EndNodeAccess_DeleteAdaptiveConfig_Handler,
		},
		{
			MethodName: "Adaptive",
			Handler:    _EndNodeAccess_Adaptive_Handler,
		},
		{
			MethodName: "FastAddInbound",
			Handler:    _EndNodeAccess_FastAddInbound_Handler,
		},
		{
			MethodName: "ObtainNewCert",
			Handler:    _EndNodeAccess_ObtainNewCert_Handler,
		},
		{
			MethodName: "TransferCert",
			Handler:    _EndNodeAccess_TransferCert_Handler,
		},
		{
			MethodName: "GetCerts",
			Handler:    _EndNodeAccess_GetCerts_Handler,
		},
		{
			MethodName: "DeleteCert",
			Handler:    _EndNodeAccess_DeleteCert_Handler,
		},
		{
			MethodName: "GetPingMetric",
			Handler:    _EndNodeAccess_GetPingMetric_Handler,
		},
		{
			MethodName: "GetNodeMetric",
			Handler:    _EndNodeAccess_GetNodeMetric_Handler,
		},
		{
			MethodName: "GetNodeGroups",
			Handler:    _EndNodeAccess_GetNodeGroups_Handler,
		},
		{
			MethodName: "SetNodeGroups",
			Handler:    _EndNodeAccess_SetNodeGroups_Handler,
		},
		{
			MethodName: "UpsertClusterUsers",
			Handler:    _EndNodeAccess_UpsertClusterUsers_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _EndNodeAccess_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/proto/rpc_server.proto",
}

const (
	CenterNodeAdmin_GetCluters_FullMethodName = "/proto.CenterNodeAdmin/GetCluters"
	CenterNodeAdmin_GetNodes_FullMethodName   = "/proto.CenterNodeAdmin/GetNodes"
)

// CenterNodeAdminClient is the client API for CenterNodeAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterNodeAdminClient interface {
	GetCluters(ctx context.Context, in *GetClutersReq, opts ...grpc.CallOption) (*GetClutersRsp, error)
	GetNodes(ctx context.Context, in *GetNodesReq, opts ...grpc.CallOption) (*GetNodesRsp, error)
}

type centerNodeAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterNodeAdminClient(cc grpc.ClientConnInterface) CenterNodeAdminClient {
	return &centerNodeAdminClient{cc}
}

func (c *centerNodeAdminClient) GetCluters(ctx context.Context, in *GetClutersReq, opts ...grpc.CallOption) (*GetClutersRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClutersRsp)
	err := c.cc.Invoke(ctx, CenterNodeAdmin_GetCluters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerNodeAdminClient) GetNodes(ctx context.Context, in *GetNodesReq, opts ...grpc.CallOption) (*GetNodesRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesRsp)
	err := c.cc.Invoke(ctx, CenterNodeAdmin_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterNodeAdminServer is the server API for CenterNodeAdmin service.
// All implementations must embed UnimplementedCenterNodeAdminServer
// for forward compatibility.
type CenterNodeAdminServer interface {
	GetCluters(context.Context, *GetClutersReq) (*GetClutersRsp, error)
	GetNodes(context.Context, *GetNodesReq) (*GetNodesRsp, error)
	mustEmbedUnimplementedCenterNodeAdminServer()
}

// UnimplementedCenterNodeAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCenterNodeAdminServer struct{}

func (UnimplementedCenterNodeAdminServer) GetCluters(context.Context, *GetClutersReq) (*GetClutersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCluters not implemented")
}
func (UnimplementedCenterNodeAdminServer) GetNodes(context.Context, *GetNodesReq) (*GetNodesRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedCenterNodeAdminServer) mustEmbedUnimplementedCenterNodeAdminServer() {}
func (UnimplementedCenterNodeAdminServer) testEmbeddedByValue()                         {}

// UnsafeCenterNodeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterNodeAdminServer will
// result in compilation errors.
type UnsafeCenterNodeAdminServer interface {
	mustEmbedUnimplementedCenterNodeAdminServer()
}

func RegisterCenterNodeAdminServer(s grpc.ServiceRegistrar, srv CenterNodeAdminServer) {
	// If the following call pancis, it indicates UnimplementedCenterNodeAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CenterNodeAdmin_ServiceDesc, srv)
}

func _CenterNodeAdmin_GetCluters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClutersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterNodeAdminServer).GetCluters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterNodeAdmin_GetCluters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterNodeAdminServer).GetCluters(ctx, req.(*GetClutersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterNodeAdmin_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterNodeAdminServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterNodeAdmin_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterNodeAdminServer).GetNodes(ctx, req.(*GetNodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CenterNodeAdmin_ServiceDesc is the grpc.ServiceDesc for CenterNodeAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CenterNodeAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CenterNodeAdmin",
	HandlerType: (*CenterNodeAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCluters",
			Handler:    _CenterNodeAdmin_GetCluters_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _CenterNodeAdmin_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/proto/rpc_server.proto",
}

const (
	CenterNodeAccess_HeartBeat_FullMethodName    = "/proto.CenterNodeAccess/HeartBeat"
	CenterNodeAccess_RegisterNode_FullMethodName = "/proto.CenterNodeAccess/RegisterNode"
)

// CenterNodeAccessClient is the client API for CenterNodeAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterNodeAccessClient interface {
	HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatRsp, error)
	RegisterNode(ctx context.Context, in *RegisterNodeReq, opts ...grpc.CallOption) (*RegisterNodeRsp, error)
}

type centerNodeAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterNodeAccessClient(cc grpc.ClientConnInterface) CenterNodeAccessClient {
	return &centerNodeAccessClient{cc}
}

func (c *centerNodeAccessClient) HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartBeatRsp)
	err := c.cc.Invoke(ctx, CenterNodeAccess_HeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *centerNodeAccessClient) RegisterNode(ctx context.Context, in *RegisterNodeReq, opts ...grpc.CallOption) (*RegisterNodeRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeRsp)
	err := c.cc.Invoke(ctx, CenterNodeAccess_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterNodeAccessServer is the server API for CenterNodeAccess service.
// All implementations must embed UnimplementedCenterNodeAccessServer
// for forward compatibility.
type CenterNodeAccessServer interface {
	HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatRsp, error)
	RegisterNode(context.Context, *RegisterNodeReq) (*RegisterNodeRsp, error)
	mustEmbedUnimplementedCenterNodeAccessServer()
}

// UnimplementedCenterNodeAccessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCenterNodeAccessServer struct{}

func (UnimplementedCenterNodeAccessServer) HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedCenterNodeAccessServer) RegisterNode(context.Context, *RegisterNodeReq) (*RegisterNodeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCenterNodeAccessServer) mustEmbedUnimplementedCenterNodeAccessServer() {}
func (UnimplementedCenterNodeAccessServer) testEmbeddedByValue()                          {}

// UnsafeCenterNodeAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterNodeAccessServer will
// result in compilation errors.
type UnsafeCenterNodeAccessServer interface {
	mustEmbedUnimplementedCenterNodeAccessServer()
}

func RegisterCenterNodeAccessServer(s grpc.ServiceRegistrar, srv CenterNodeAccessServer) {
	// If the following call pancis, it indicates UnimplementedCenterNodeAccessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CenterNodeAccess_ServiceDesc, srv)
}

func _CenterNodeAccess_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterNodeAccessServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterNodeAccess_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterNodeAccessServer).HeartBeat(ctx, req.(*HeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CenterNodeAccess_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterNodeAccessServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterNodeAccess_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterNodeAccessServer).RegisterNode(ctx, req.(*RegisterNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CenterNodeAccess_ServiceDesc is the grpc.ServiceDesc for CenterNodeAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CenterNodeAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CenterNodeAccess",
	HandlerType: (*CenterNodeAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _CenterNodeAccess_HeartBeat_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _CenterNodeAccess_RegisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/proto/rpc_server.proto",
}
